// <auto-generated />
using System;
using System.Numerics;
using Argus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Argus.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903082032_AddPonsLaunchCalldata")]
    partial class AddPonsLaunchCalldata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Argus.Data.Entities.ChainCursor", b =>
                {
                    b.Property<long>("ChainId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastProcessedBlock")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChainId");

                    b.ToTable("ChainCursors");
                });

            modelBuilder.Entity("Argus.Data.Entities.TokenDeployment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BlockHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("ChainId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<BigInteger?>("CreatorBuyQuote")
                        .HasColumnType("numeric");

                    b.Property<string>("DeployerAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactoryAddress")
                        .HasColumnType("text");

                    b.Property<string>("LaunchpadName")
                        .HasColumnType("text");

                    b.Property<string>("PairTokenAddress")
                        .HasColumnType("text");

                    b.Property<int?>("TokenDecimals")
                        .HasColumnType("integer");

                    b.Property<string>("TokenName")
                        .HasColumnType("text");

                    b.Property<string>("TokenSymbol")
                        .HasColumnType("text");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChainId", "ContractAddress")
                        .IsUnique();

                    b.ToTable("TokenDeployments");
                });

            modelBuilder.Entity("Argus.Data.Entities.TokenDeploymentInsider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TokenDeploymentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenDeploymentId", "Address")
                        .IsUnique();

                    b.ToTable("TokenDeploymentInsiders");
                });

            modelBuilder.Entity("Argus.Data.Entities.TokenDeploymentInsider", b =>
                {
                    b.HasOne("Argus.Data.Entities.TokenDeployment", "TokenDeployment")
                        .WithMany("Insiders")
                        .HasForeignKey("TokenDeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenDeployment");
                });

            modelBuilder.Entity("Argus.Data.Entities.TokenDeployment", b =>
                {
                    b.Navigation("Insiders");
                });
#pragma warning restore 612, 618
        }
    }
}
