// <auto-generated />
using System;
using Argus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Argus.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Argus.Data.Entities.ChainCursor", b =>
                {
                    b.Property<long>("ChainId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastProcessedBlock")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChainId");

                    b.ToTable("ChainCursors");
                });

            modelBuilder.Entity("Argus.Data.Entities.TokenDeployment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BlockHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("ChainId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeployerAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactoryAddress")
                        .HasColumnType("text");

                    b.Property<string>("LaunchpadName")
                        .HasColumnType("text");

                    b.Property<int?>("TokenDecimals")
                        .HasColumnType("integer");

                    b.Property<string>("TokenName")
                        .HasColumnType("text");

                    b.Property<string>("TokenSymbol")
                        .HasColumnType("text");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChainId", "ContractAddress")
                        .IsUnique();

                    b.ToTable("TokenDeployments");
                });
#pragma warning restore 612, 618
        }
    }
}
