<Project>
	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>

		<ImplicitUsings>enable</ImplicitUsings>

		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>

		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	</PropertyGroup>
</Project>