<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Mediator.SourceGenerator" PrivateAssets="all" ExcludeAssets="runtime">
			<IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\FocusTemplate.Data\FocusTemplate.Data.csproj" />
		<ProjectReference Include="..\..\FocusTemplate.ServiceDefaults\FocusTemplate.ServiceDefaults.csproj" />
		<ProjectReference Include="..\FocusTemplate.Admin.Shared\FocusTemplate.Admin.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../spec/**/*.tsp" LinkBase="spec" />
		<None Include="tspconfig.yaml" />

		<Content Include="openapi.yaml" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>