// <auto-generated />
using System;
using FocusTemplate.Data;
using FocusTemplate.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FocusTemplate.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923105829_WeatherStations")]
    partial class WeatherStations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "alert_kind", new[] { "temperature_above_maximum", "temperature_below_minimum" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "station_status", new[] { "active", "maintenance", "retired" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FocusTemplate.Data.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<AlertKind>("Kind")
                        .HasColumnType("alert_kind")
                        .HasColumnName("kind");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<long>("ObservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("observation_id");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("StationId", "ResolvedAt")
                        .HasDatabaseName("ix_alerts_station_id_resolved_at");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("FocusTemplate.Data.Entities.Observation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("HumidityPercent")
                        .HasColumnType("integer")
                        .HasColumnName("humidity_percent");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<double>("PressureHpa")
                        .HasColumnType("double precision")
                        .HasColumnName("pressure_hpa");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature_c");

                    b.HasKey("Id")
                        .HasName("pk_observations");

                    b.HasIndex("StationId", "MeasuredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_observations_station_id_measured_at");

                    b.ToTable("observations", null, t =>
                        {
                            t.HasCheckConstraint("CK_observations_humidity_percent_Range", "humidity_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_observations_pressure_hpa_Range", "pressure_hpa BETWEEN 800.0 AND 1200.0");

                            t.HasCheckConstraint("CK_observations_temperature_c_Range", "temperature_c BETWEEN -100.0 AND 100.0");
                        });
                });

            modelBuilder.Entity("FocusTemplate.Data.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)")
                        .HasColumnName("location");

                    b.Property<int?>("MaxTemperatureC")
                        .HasColumnType("integer")
                        .HasColumnName("max_temperature_c");

                    b.Property<int?>("MinTemperatureC")
                        .HasColumnType("integer")
                        .HasColumnName("min_temperature_c");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<StationStatus>("Status")
                        .HasColumnType("station_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("OwnerId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_stations_owner_id_code");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("FocusTemplate.Data.Entities.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("summary");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer")
                        .HasColumnName("temperature_c");

                    b.HasKey("Id")
                        .HasName("pk_weather_forecasts");

                    b.HasIndex("StationId", "Date")
                        .HasDatabaseName("ix_weather_forecasts_station_id_date");

                    b.ToTable("weather_forecasts", (string)null);
                });

            modelBuilder.Entity("FocusTemplate.Data.Entities.Alert", b =>
                {
                    b.HasOne("FocusTemplate.Data.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_stations_station_id");
                });

            modelBuilder.Entity("FocusTemplate.Data.Entities.Observation", b =>
                {
                    b.HasOne("FocusTemplate.Data.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observations_stations_station_id");
                });

            modelBuilder.Entity("FocusTemplate.Data.Entities.WeatherForecast", b =>
                {
                    b.HasOne("FocusTemplate.Data.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weather_forecasts_stations_station_id");
                });
#pragma warning restore 612, 618
        }
    }
}
