<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" />
		<PackageReference Include="Yarp.ReverseProxy" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\FocusTemplate.ServiceDefaults\FocusTemplate.ServiceDefaults.csproj" />
		<ProjectReference Include="..\FocusTemplate.Admin.Shared\FocusTemplate.Admin.Shared.csproj" />
		<ProjectReference Include="..\FocusTemplate.Admin.Web\FocusTemplate.Admin.Web.csproj" />
	</ItemGroup>

</Project>