<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UserSecretsId>f17904a0-2527-4a67-8814-34dd2ac5efe2</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.Blazor" />
		<PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" />
		<PackageReference Include="CommunityToolkit.Aspire.Hosting.Umami" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FocusTemplate.Api\FocusTemplate.Api.csproj" />
		<ProjectReference Include="..\FocusTemplate.Data\FocusTemplate.Data.csproj" IsAspireProjectResource="false" />
		<ProjectReference Include="..\FocusTemplate.Web.Bff\FocusTemplate.Web.Bff.csproj" />
	</ItemGroup>

</Project>