<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UserSecretsId>f17904a0-2527-4a67-8814-34dd2ac5efe2</UserSecretsId>
		<AspireUseCliBundle>true</AspireUseCliBundle>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.Blazor" />
		<PackageReference Include="Aspire.Hosting.DevTunnels" />
		<PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
		<PackageReference Include="Aspire.Hosting.Maui" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" />
		<PackageReference Include="CommunityToolkit.Aspire.Hosting.Umami" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\admin\FocusTemplate.Admin.Api\FocusTemplate.Admin.Api.csproj" />
		<ProjectReference Include="..\FocusTemplate.Data\FocusTemplate.Data.csproj" IsAspireProjectResource="false" />
		<ProjectReference Include="..\admin\FocusTemplate.Admin.Web.Bff\FocusTemplate.Admin.Web.Bff.csproj" />
		<ProjectReference Include="..\public\FocusTemplate.Public.Api\FocusTemplate.Public.Api.csproj" />
		<ProjectReference Include="..\intel\FocusTemplate.Intel.Worker\FocusTemplate.Intel.Worker.csproj" />
	</ItemGroup>

</Project>