<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../FocusTemplate.Primitives/FocusTemplate.Primitives.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="tspconfig.yaml" />
	</ItemGroup>

</Project>