<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
		<PackageReference Include="EFCore.CheckConstraints" />
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="Vogen" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FocusTemplate.Primitives\FocusTemplate.Primitives.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Entities\**\*Configuration.cs">
			<DependentUpon>$([System.Text.RegularExpressions.Regex]::Replace('%(Filename)', 'Configuration$', '')).cs</DependentUpon>
		</Compile>
	</ItemGroup>
</Project>