<Project Sdk="Microsoft.NET.Sdk.Worker">

	<ItemGroup>
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Nethereum.Web3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\FocusTemplate.Data\FocusTemplate.Data.csproj" />
		<ProjectReference Include="..\..\FocusTemplate.ServiceDefaults\FocusTemplate.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
