emit:
  - "@spatialfocus/typespec-http-csharp-slim"
options:
  "@spatialfocus/typespec-http-csharp-slim":
    emitter-output-dir: "{output-dir}"
    output-type: primitives
    generated-dir: "generated"